#this is my Github Actions test file from Step 4

name: hello-world

on: push
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - run: make install
      - run: make gff
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make init-jest
      - run: make test-all
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make lint